name: CMake Build

on:
  push:
    branches: [Mac-conda]

  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build-mac:
    name: Build Mac OS
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: 2.1. Obtaining OpenSees Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3.0.4
        with:
            activate-environment: ops-mac
            python-version: 3.11
      # - name: XCode Command Line Tools is already installed.
      - name: Install other dependencies via Homebrew
        run: |
         ln -s /opt/homebrew/bin/gcc-13 /usr/local/bin/gcc
         ln -s /opt/homebrew/bin/gfortran-13 /usr/local/bin/gfortran
         brew install eigen
         brew install hdf5
         brew install open-mpi
         brew install scalapack
         sudo ln -sf /opt/homebrew/include/eigen3/Eigen /opt/homebrew/include/Eigen
      - name: MUMPS
        run: |
          git clone https://github.com/OpenSees/mumps.git
          cd mumps
          mkdir build
          cd build
          cmake .. -Darith=d
          cmake --build . --config Release --parallel 4
      - name: 2.3.2. Building the OpenSees Applications and Python module
        run: |
          mkdir build
          cd build
          conda activate ops-mac
          conda info
          cmake .. -DMUMPS_DIR=$PWD/../../mumps/build
          cmake --build . --target OpenSees -j8
          cmake --build . --target OpenSeesPy -j8
          mv ./OpenSeesPy.dylib ./opensees.so
      - name: Verification OpenSeesPySP
        run: |
          export PYTHONPATH="./build/"
          python3 -c "import sys; print(sys.path)"
          python3 ./EXAMPLES/ExamplePython/example_variable_analysis.py
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
            name: OpenSees_Mac
            path: |
              ./build/OpenSees
              ./build/opensees.so
